name: flutter_luckin_coffee
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # 路由管理三方Fluro
  # https://github.com/theyakka/fluro
  fluro: ^1.7.8
  # 本地存储
  shared_preferences: ^0.5.6+3
  # toast提示框 loading等
  flutter_easyloading: ^2.2.0
  # 轮播图
  flutter_swiper: ^1.1.6
  # 获取权限
  permission_handler: ^5.0.1+1
  # 缓存
  path_provider: ^1.1.2
  # 图片缓存
  cached_network_image: ^2.3.2+1
  # 加密算法函数
  crypto: ^2.0.6
  # http请求
  dio: ^3.0.9
  # 设备信息
  device_info: ^1.0.0
  # 获取应用信息
  package_info: ^0.4.3+2
  # 屏幕适配
  flutter_screenutil: ^4.0.3+1
  # 状态管理
  provider: ^4.3.3
  # 百度定位插件
  flutter_bmflocation: ^1.0.4
  # 基础地图依赖添加
  flutter_baidu_mapapi_map: ^2.0.1
  # 检索组件依赖添加
  flutter_baidu_mapapi_search: ^2.0.1
  # 计算工具依赖添加
  flutter_baidu_mapapi_utils: ^2.0.1
  # 替换应用图标
  flutter_launcher_icons: ^0.8.0
  # 渲染html
  flutter_html: ^1.1.1
  # 带有徽标的底部导航
  convex_bottom_bar: ^2.7.1+2
  # 下拉刷新上拉加载
  pull_to_refresh: ^1.6.3
  # 日期选择器
  flutter_datetime_picker: ^1.5.0
  # 时间格式化
  date_format: ^1.0.9
  # 城市选择器
  city_pickers: ^0.2.0
  # 图片相册或者拍照
  image_picker: ^0.6.7+22
  # 裁剪图片
  image_cropper: ^1.3.1
  # 调用支付宝支付
  flutter_alipay: ^1.0.0
  # 虚线边框
  dotted_border: ^1.0.7
  # 选择文件
  file_picker: ^1.3.8
  # 视频播放器
  chewie: ^0.12.2
  video_player: ^1.0.1
  # 图片浏览
  photo_view: ^0.10.3
  # 保存图片到本地
  image_gallery_saver: ^1.6.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
#替换应用图标 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/images/home/
    - lib/assets/images/menu/
    - lib/assets/images/mine/
    - lib/assets/images/order/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
      - family: iconfont
        fonts:
          - asset: lib/assets/fonts/iconfont.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
